$:.push File.expand_path("../lib", __FILE__)

# Maintain your gem's version:
require "houston/ci/version"

# Describe your gem and declare its dependencies:
Gem::Specification.new do |spec|
  spec.name          = "houston-ci"
  spec.version       = Houston::Ci::VERSION
  spec.authors       = ["Bob Lail"]
  spec.email         = ["bob.lailfamily@gmail.com"]

  spec.summary       = "Track and report on test results with Houston"
  spec.homepage      = "https://github.com/houston/houston-ci"

  spec.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  spec.require_paths = ["lib"]
  spec.test_files = Dir["test/**/*"]

  spec.add_dependency "houston-core", ">= 0.8.0.pre"

  # Used to create image charts for embedding in email
  # TODO: this product is deprecated, so find a replacement
  # This is used only StaticChart,
  # which is used only in StaticChartHelper,
  # which is used only by the Test Results email
  spec.add_dependency "googlecharts", "~> 1.6.12"

  # This is a runtime dependency because Houston uses it to parse
  # code coverage data generated by simplecov
  spec.add_dependency "simplecov", "~> 0.9.1"

  spec.add_development_dependency "bundler", "~> 1.11.2"
  spec.add_development_dependency "rake", "~> 10.0"
end
